print(">>>>> OdaiHTN Tests")
dofile("Data Files/MWSE/mods/sb_htn_tests/ActionEffectTests.lua")
dofile("Data Files/MWSE/mods/sb_htn_tests/BaseContextTests.lua")
dofile("Data Files/MWSE/mods/sb_htn_tests/DomainBuilderTests.lua")
dofile("Data Files/MWSE/mods/sb_htn_tests/DomainTests.lua")
dofile("Data Files/MWSE/mods/sb_htn_tests/FuncConditionTests.lua")
dofile("Data Files/MWSE/mods/sb_htn_tests/FuncOperatorTests.lua")
dofile("Data Files/MWSE/mods/sb_htn_tests/PlannerTests.lua")
dofile("Data Files/MWSE/mods/sb_htn_tests/PrimitiveTaskTests.lua")
dofile("Data Files/MWSE/mods/sb_htn_tests/SelectorTests.lua")
dofile("Data Files/MWSE/mods/sb_htn_tests/SequenceTests.lua")
print("<<<<<")
